### ISSUE TITLE
ipn doesn't work in sanbox.

### ISSUE THREAD

**Issue by devsan1** [sslcommerz/SSLCommerz-Laravel#10]
I have been trying to integrate sslcommerz project in laravel using your github codes. Everything works fine except OPT code isn't sent to the mobile number provide duing post request.
custPhone = 01558121408
It always bypass the the IPN function. It never hits this function.
[
![Screenshot from 2019-10-31 12-30-21](https://user-images.githubusercontent.com/54181470/67946887-40326e80-fbda-11e9-8df2-8e7a9302a6b9.png)
](url)

In the OTP page, If I pass any number It loads success and never hits IPN method.

**Comment by rkbi** [comment]
You don't need OTP in sandbox. The idea of sandbox is to emulate the API response in different types of transaction without actually doing the transaction.

**Comment by rkbi** [comment]
> It always bypass the the IPN function. It never hits this function.

IPN __DOES__ work on sandbox. You are probably trying from your local dev machine. Gateway server can not reach your local computer (without public IP / reverse proxy) with IPN. Use a test server on public internet.
