### ISSUE TITLE
Cannot use isset() on the result of an expression (you can use "null !== expression" instead)

### ISSUE THREAD

**Issue by devdict** [sslcommerz/SSLCommerz-Laravel#12]
I found this error 

**Cannot use isset() on the result of an expression (you can use "null !== expression" instead)**

in **app/Library/SslCommerz/AbstractSslCommerz.php:97**

```
 if(isset($this->getApiUrl()) && $this->getApiUrl() == 'https://securepay.sslcommerz.com') {
                   $response = json_encode(['status' => 'SUCCESS', 'data' => $sslcz['GatewayPageURL'], 'logo' => $sslcz['storeLogo']]);
                } else {
                    $response = json_encode(['status' => 'success', 'data' => $sslcz['GatewayPageURL'], 'logo' => $sslcz['storeLogo']]);
                }
```

If replace this by 
`$response = json_encode(['status' => 'SUCCESS', 'data' => $sslcz['GatewayPageURL'], 'logo' => $sslcz['storeLogo']]);`

It work

**Comment by rkbi** [comment]
bug fixed with #13
