### ISSUE TITLE
Session expires.

### ISSUE THREAD

**Issue by imrulhasan273** [sslcommerz/SSLCommerz-Laravel#18]
After click on success button the session expires. How to keep the session?

**Comment by ihrifat2** [comment]
did you found any solution?

**Comment by rkbi** [comment]
This is a general issue, not only SSLCommerz specific. When redirect to another domain, browser destroys the session by default as a security measure. You can workaround this by setting `'same_site' => "none"` on `config/session.php` file.

To learn more about samesite cookies - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
