### ISSUE TITLE
I used this code and getting validation Fail after payment in my sandbox account

### ISSUE THREAD

**Issue by kabircse** [sslcommerz/SSLCommerz-Laravel#2]
I used this code to my laravel 5.6 project and getting false on $sslc->orderValidate .
But payment is success on sandbox account. 
Could you check this code ?

**Comment by rassemdev** [comment]
@kabircse apni integrate korte parsen?

**Comment by kabircse** [comment]
> @kabircse apni integrate korte parsen?

Yes, I have done.

**Comment by rassemdev** [comment]
Can you share me the code!

**Comment by kabircse** [comment]
> Can you share me the code!

After searching the files I will share you.
