### ISSUE TITLE
Error in Communication

### ISSUE THREAD

**Issue by ghost** [sslcommerz/SSLCommerz-Laravel#24]
I have all ready integration complete by documentation, but I have got an error message. "Error in Communication"
Class 'App\Library\SslCommerz\SslCommerzNotification' not found
https://prnt.sc/tx321e

**Comment by ghost** [comment]
Ok, guys problem solved. just change this "app/Library/sslcommerz" to  "app/Library/SslCommerz" its case sensitive.

**Comment by rkbi** [comment]
> Ok, guys problem solved. just change this "app/Library/sslcommerz" to "app/Library/SslCommerz" its case sensitive.

On which file did you need to change? Please let us know. It's already in camelcase as far I can find.
