### ISSUE TITLE
Why projectPath need in config?

### ISSUE THREAD

**Issue by sandofvega** [sslcommerz/SSLCommerz-Laravel#36]
```php
'projectPath' => env('PROJECT_PATH')
```

That is the use case of `projectPath`?

**Comment by palatok** [comment]
`'projectPath'` is the domain name. if your `'projectPath'` is `http://example.com` and your success url is `/payment/success`, then SSLCommerz will redirect you to `http://example.com/payment/success` after payment is successful. `'projectPath'` is important when you have `https` enabled. However the `'projectPath'` is not being used right now. I have made a pull request to use `'projectPath'`
