### ISSUE TITLE
returning  from SSL to my project, destroyong the session

### ISSUE THREAD

**Issue by momit-litu** [sslcommerz/SSLCommerz-Laravel#38]
Hi,
Thank you for you code.
I was trying to implement the code into my laravel project, i have been able to successfull payment. 
but the problem is when i redirect back to my success/fail route i found no session remains.

i had tried to sent the cookies through header . but that didnt worked either.
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Cookie: laravel_session={$_COOKIE['laravel_session']}"));

any suggestion?
thank you

**Comment by rkbi** [comment]
https://github.com/sslcommerz/SSLCommerz-Laravel/issues/18#issuecomment-660803772

**Comment by zhasan0** [comment]
@momit-litu did you fix it brother?

'secure' => env('SESSION_SECURE_COOKIE', false),
'same_site' => null,

I made above configuration. But not working.

If I set this 
same_site' => "none"
Then I can't login

**Comment by zhasan0** [comment]
Solution for laravel 8-
config/session.php

`'secure' => true,
'same_site' => 'none'`

Thanks

**Comment by ali-azgar-rakib** [comment]
> Solution for laravel 8- config/session.php
> 
> `'secure' => true, 'same_site' => 'none'`
> 
> Thanks

Laravel 10 . Not working for me

**Comment by AfzalSabbir** [comment]
> 

You can use: https://github.com/AfzalSabbir/SSLaraCommerz

**Comment by AfzalSabbir** [comment]
> > Solution for laravel 8- config/session.php
> > `'secure' => true, 'same_site' => 'none'`
> > Thanks
> 
> Laravel 10 . Not working for me

You can use: https://github.com/AfzalSabbir/SSLaraCommerz
